# Generated by Django 2.2.4 on 2019-10-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(default='446100', max_length=6)),
                ('city', models.CharField(default='Самара', max_length=200)),
                ('street', models.CharField(default='Николая-Панова', max_length=200)),
                ('buildingNumber', models.CharField(default='144', max_length=6)),
                ('housing', models.CharField(blank=True, default='', max_length=6)),
                ('structure', models.CharField(blank=True, default='', max_length=6)),
                ('flat', models.CharField(blank=True, default='25', max_length=6)),
                ('oblast', models.CharField(blank=True, default='Самарская обл.', max_length=200)),
                ('rayon', models.CharField(blank=True, default='Волжский р-он.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default='0000 0000 0000 0000 0000', max_length=24)),
                ('correspondent_account_number', models.CharField(blank=True, default='0000 0000 0000 0000 0000', max_length=24)),
                ('bic', models.CharField(blank=True, default='000 000 000', max_length=11)),
                ('bank_name', models.CharField(blank=True, default='ОАО Сбербанк', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Иван', max_length=30)),
                ('part_name', models.CharField(default='Иванович', max_length=30)),
                ('last_name', models.CharField(default='Иванов', max_length=30)),
                ('position', models.CharField(default='Инженер', max_length=300)),
                ('phone_number', models.CharField(default='89276976453', max_length=12)),
                ('email', models.EmailField(default='ivan@gmail.com', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file_name', models.CharField(default='file name', max_length=500)),
                ('file_type', models.CharField(default='pdf', max_length=20)),
                ('class_name', models.CharField(default='SberPoFormeBanka', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PostAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(default='446100', max_length=6)),
                ('city', models.CharField(default='Самара', max_length=200)),
                ('street', models.CharField(default='Николая-Панова', max_length=200)),
                ('buildingNumber', models.CharField(default='144', max_length=6)),
                ('housing', models.CharField(blank=True, default='', max_length=6)),
                ('structure', models.CharField(blank=True, default='', max_length=6)),
                ('flat', models.CharField(blank=True, default='25', max_length=6)),
                ('oblast', models.CharField(blank=True, default='Самарская обл.', max_length=200)),
                ('rayon', models.CharField(blank=True, default='Волжский р-он.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalClientInfo',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('product', models.CharField(choices=[('1', 'готовое жилье'), ('2', 'рефинансирование'), ('3', 'строящееся жилье'), ('4', 'под залог недвижимости')], default=('1', 'готовое жилье'), max_length=50)),
                ('property', models.CharField(choices=[('1', 'квартира'), ('2', 'апартаменты'), ('3', 'таунхаус'), ('4', 'жилой дом с участком')], default=('1', 'квартира'), max_length=50)),
                ('full_insurance', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default=('yes', 'да'), max_length=50)),
                ('registration', models.CharField(choices=[('1', 'постоянная'), ('2', 'временная')], default=('1', 'постоянная'), max_length=50)),
                ('address_of_registration', models.CharField(default='Адрес регистрации (постоянная/временная)', max_length=10000)),
                ('actual_address', models.CharField(default='Адрес фактического проживания', max_length=10000)),
                ('count_of_children', models.CharField(default='0', max_length=2)),
                ('family_status', models.CharField(choices=[('not maried', 'не женат/не замужем'), ('maried', 'женат/замужем'), ('divorced', 'в разводе'), ('single/widow', 'вдовец/вдова')], default=('not maried', 'не женат/не замужем'), max_length=13)),
                ('education_status', models.CharField(choices=[('below the average', 'ниже среднего'), ('the average', 'среднее'), ('specialized secondary', 'второе высшее'), ('incomplete higher education', 'незаконченное высшее образование'), ('higher', 'высшее'), ('academic degree', 'академическая степень')], default=('below the average', 'ниже среднего'), max_length=50)),
                ('work_expireance', models.CharField(choices=[('1', 'менее 1 года'), ('2', '1 - 2 года'), ('3', '2 - 5 лет'), ('4', 'более 5 лет')], default=('1', 'менее 1 года'), max_length=50)),
                ('position_category', models.CharField(choices=[('руководитель среднего сзвена', 'руководитель среднего сзвена'), ('Руководитель высшего звена', 'Руководитель высшего звена'), ('специалист', 'специалист'), ('рабочий', 'рабочий'), ('высококвалифицированный специалист', 'высококвалифицированный специалист'), ('руководитель низшего звена', 'руководитель низшего звена'), ('военносулжащий', 'военносулжащий'), ('обслуживающий персонал', 'обслуживающий персонал')], default=('руководитель среднего сзвена', 'руководитель среднего сзвена'), max_length=50)),
                ('work_type', models.CharField(choices=[('1', 'по найму'), ('2', 'ИП'), ('3', 'адвокат'), ('4', 'собственник бизнеса'), ('5', 'не работаю')], default=('1', 'по найму'), max_length=50)),
                ('marriage_contract', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default=('yes', 'да'), max_length=50)),
                ('immovable_property', models.CharField(choices=[('1', 'Квартира'), ('2', 'апартаменты'), ('3', 'таунхаус'), ('4', 'дом с участком'), ('5', 'иное')], default=('1', 'Квартира'), max_length=50)),
                ('rezident_of_usa', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default=('yes', 'да'), max_length=50)),
                ('rezident_of_other_goverment', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default=('yes', 'да'), max_length=50)),
                ('foreign_citizen', models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default=('yes', 'да'), max_length=50)),
                ('additional_work', models.CharField(choices=[('1', 'по найму'), ('2', 'ИП'), ('3', 'адвокат'), ('4', 'собственник бизнеса'), ('5', 'не работаю')], default=('1', 'по найму'), max_length=50)),
                ('additional_work_expireance', models.CharField(choices=[('1', 'до 4 мес'), ('2', '4 - 6 мес'), ('3', 'от 6 мес'), ('4', 'до 1 года'), ('5', '1 - 2 года'), ('6', '2 - 5 лет'), ('7', 'более 5 лет')], default=('1', 'до 4 мес'), max_length=50)),
                ('additional_work_category', models.CharField(choices=[('руководитель среднего сзвена', 'руководитель среднего сзвена'), ('Руководитель высшего звена', 'Руководитель высшего звена'), ('специалист', 'специалист'), ('рабочий', 'рабочий'), ('высококвалифицированный специалист', 'высококвалифицированный специалист'), ('руководитель низшего звена', 'руководитель низшего звена'), ('военносулжащий', 'военносулжащий'), ('обслуживающий персонал', 'обслуживающий персонал')], default=('руководитель среднего сзвена', 'руководитель среднего сзвена'), max_length=50)),
                ('income_of_main_work', models.CharField(default='доход от основной работы', max_length=200)),
                ('income_of_additional_work', models.CharField(default='доход от работы по совместительству', max_length=200)),
                ('mark_of_car', models.CharField(default='марка авто ', max_length=200)),
                ('year_of_manufacture_of_car', models.CharField(default='год выпуска авто', max_length=200)),
                ('car_valuation', models.CharField(default='оценка стоимости авто', max_length=200)),
                ('market_value_of_real_estate', models.CharField(default='Рыночная стоимость недвижимости', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='INN',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('inn_number', models.CharField(default='123-123-123 00', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SNILS',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('snils_number', models.CharField(default='123-123-123 00', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='clients file name', max_length=500)),
                ('file_path', models.CharField(default='/', max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('serial', models.CharField(default='0000', max_length=4)),
                ('number', models.CharField(default='000000', max_length=6)),
                ('_from', models.CharField(default='отделом ФМС', max_length=200)),
                ('gender', models.CharField(default='м', max_length=5)),
                ('birthday', models.DateField(default='1999-01-01')),
                ('code_of', models.CharField(default='344-222', max_length=8)),
            ],
            options={
                'unique_together': {('client', 'serial', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('full_name', models.CharField(default='Сбербанк', max_length=10000)),
                ('accountent_number', models.CharField(default='1345678911', max_length=10)),
                ('hr_number', models.CharField(default='1345678911', max_length=10)),
                ('inn_number', models.CharField(default='1345678911', max_length=100)),
                ('field_of_activity', models.CharField(default='IT', max_length=100)),
                ('incorparation_form', models.CharField(choices=[('1', 'ООО'), ('2', 'ПАО'), ('3', 'ЗАО\\АО'), ('4', 'гос.учреждение'), ('5', 'иное(здесь строка)')], default=('1', 'ООО'), max_length=13)),
                ('number_of_staff', models.CharField(choices=[('1', 'до 10'), ('2', '10-100'), ('3', '101-500'), ('4', 'более 500')], default=('1', 'до 10'), max_length=13)),
                ('work_experience', models.CharField(choices=[('1', 'до 4 мес'), ('2', '4 - 6 мес'), ('3', 'от 6 мес'), ('4', 'до 1 года'), ('5', '1 - 2 года'), ('6', '2 - 5 лет'), ('7', 'более 5 лет')], default=('1', 'до 4 мес'), max_length=13)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Address')),
                ('bank_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.BankDetail')),
                ('post_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.PostAddress')),
            ],
        ),
    ]
