# Generated by Django 2.2.1 on 2019-08-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(default='446100', max_length=6)),
                ('city', models.CharField(default='Самара', max_length=200)),
                ('street', models.CharField(default='Николая-Панова', max_length=200)),
                ('buildingNumber', models.CharField(default='144', max_length=6)),
                ('housing', models.CharField(blank=True, default='', max_length=6)),
                ('structure', models.CharField(blank=True, default='', max_length=6)),
                ('flat', models.CharField(blank=True, default='25', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, default='0000 0000 0000 0000 0000', max_length=24)),
                ('correspondent_account_number', models.CharField(blank=True, default='0000 0000 0000 0000 0000', max_length=24)),
                ('bic', models.CharField(blank=True, default='000 000 000', max_length=11)),
                ('bank_name', models.CharField(blank=True, default='ОАО Сбербанк', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Иван', max_length=30)),
                ('part_name', models.CharField(default='Иванович', max_length=30)),
                ('last_name', models.CharField(default='Иванов', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file_name', models.CharField(default='file name', max_length=500)),
                ('file_type', models.CharField(default='pdf', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SNILS',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('snils_number', models.CharField(default='123-123-123 00', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='clients file name', max_length=500)),
                ('file_path', models.CharField(default='/', max_length=1000)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('serial', models.CharField(default='0000', max_length=4)),
                ('number', models.CharField(default='000000', max_length=6)),
                ('_from', models.CharField(default='отделом ФМС', max_length=200)),
                ('gender', models.CharField(default='м', max_length=5)),
                ('bith_day', models.DateField(default='1999-01-01')),
                ('bith_place', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'unique_together': {('client', 'serial', 'number')},
            },
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('full_name', models.CharField(default='Сбербанк', max_length=10000)),
                ('accountent_number', models.CharField(default='1345678911', max_length=10)),
                ('hr_number', models.CharField(default='1345678911', max_length=10)),
                ('inn_number', models.CharField(default='1345678911', max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Address')),
                ('bank_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.BankDetail')),
            ],
        ),
    ]
