# Generated by Django 2.2.1 on 2019-08-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snils',
            old_name='number',
            new_name='snils_number',
        ),
    ]
