# Generated by Django 2.2.1 on 2019-08-06 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=6)),
                ('buildingNumber', models.CharField(max_length=6)),
                ('housing', models.CharField(max_length=6)),
                ('structure', models.CharField(max_length=6)),
                ('flat', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('correspondent_account_number', models.CharField(max_length=20)),
                ('BIC', models.CharField(max_length=9)),
                ('bank_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('full_name', models.CharField(max_length=10000)),
                ('accountent_number', models.CharField(max_length=10)),
                ('hr_number', models.CharField(max_length=10)),
                ('inn_number', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Address')),
                ('bank_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.BankDetail')),
            ],
        ),
    ]
