# Generated by Django 2.2.1 on 2019-07-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientsfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='file name', max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientsfile',
            name='file_path',
            field=models.CharField(default='/', max_length=1000),
        ),
    ]
