# Generated by Django 2.2.1 on 2019-07-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20190724_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsfile',
            name='file_name',
            field=models.CharField(default='clients file name', max_length=500),
        ),
    ]
