# Generated by Django 2.2.3 on 2019-08-04 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20190804_2219'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('first_name', 'part_name', 'last_name')},
        ),
    ]
