"""
Django settings for mainapp project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9lvu(w2w0udfw&bj%!j*%7q)1!-y2lzty2+nrbrb=#@g6hz^#a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hello',
    'doc_filler_app',
    'todo',
    'clients',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mainapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mainapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),						     #0
    os.path.join(BASE_DIR, "static\\genereted_docs"),   	     #1
    os.path.join(BASE_DIR, "static\\genereted_docs\\txt"),       #2
    os.path.join(BASE_DIR, "static\\genereted_docs\\pdf"),	     #3
    os.path.join(BASE_DIR, "static\\genereted_docs\\exel"),      #4
    os.path.join(BASE_DIR, "static\\genereted_docs\\doc"),      #5
    os.path.join(BASE_DIR, "static\\template_docs"),    	  	#6
    os.path.join(BASE_DIR, "static\\template_docs\\txt"),		 #7
    os.path.join(BASE_DIR, "static\\template_docs\\pdf"),		 #8
    os.path.join(BASE_DIR, "static\\template_docs\\exel"),	     #9
    os.path.join(BASE_DIR, "static\\template_docs\\doc"),		 #10
    os.path.join(BASE_DIR, "static\\css"),                      #11
    os.path.join(BASE_DIR, "static\\js"),                       #12
    os.path.join(BASE_DIR, "static\\img"),                       #13
]

TXT_TEMPL_DIR = STATICFILES_DIRS[7]
PDF_TEMPL_DIR = STATICFILES_DIRS[8]
EXEL_TEMPL_DIR = STATICFILES_DIRS[9]
DOC_TEMPL_DIR = STATICFILES_DIRS[10]

PDF_EXT = '.pdf'
DOC_EXT = '.doc'
DOCX_EXT = '.docx'
EXEL_EXT = '.xls'
TXT_EXT = '.txt'

PDF = 'pdf'
DOC = 'doc'
DOCX = 'docx'
EXEL = 'xls'
TXT = 'txt'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media');
MEDIA_URL = '/media/';