pip install django-cms
pip install djangocms-admin-style
pip install django-treebeard
pip install djangocms-text-ckeditor
pip install djangocms-link
pip install djangocms-style
pip install djangocms-googlemap
pip install djangocms-snippet
pip install djangocms-video
pip install djangocms-file
pip install djangocms-picture
pip install djangocms-bootstrap4
pip install easy_thumbnails
pip install django-filer
pip install django-classy-tags
pip install django-sekizai
pip install django-mptt
pip install html5lib
pip install Pillow