# Generated by Django 2.2.8 on 2019-12-06 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCredit',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('type', models.CharField(blank=True, default='Потребительский', max_length=100)),
                ('creditor_name', models.CharField(blank=True, default='Сбербанки', max_length=100)),
                ('date_start', models.DateField(default='2000-01-01')),
                ('date_end', models.DateField(default='2005-01-01')),
                ('currency', models.CharField(blank=True, default='Руб', max_length=100)),
                ('value', models.CharField(blank=True, default='100000', max_length=100)),
                ('month_pay', models.CharField(blank=True, default='1000', max_length=100)),
                ('leftover', models.CharField(blank=True, default='1000', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRelative',
            fields=[
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clients.Client')),
                ('first_name', models.CharField(default='Гена', max_length=30)),
                ('part_name', models.CharField(default='Иванович', max_length=30)),
                ('last_name', models.CharField(default='Иванов', max_length=30)),
                ('position', models.CharField(default='Рыбак', max_length=300)),
                ('relation_degree', models.CharField(default='Брат', max_length=300)),
                ('phone_number', models.CharField(default='89276976443', max_length=12)),
                ('email', models.EmailField(default='genaiv@gmail.com', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='aliment',
            field=models.CharField(default='Алименты', max_length=200),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='average_income',
            field=models.CharField(default='средний доход до вычета налогов', max_length=200),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='home_phone_number',
            field=models.CharField(default='89276976453', max_length=12),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='model_of_car',
            field=models.CharField(default='модель авто ', max_length=200),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='monetary_obligations',
            field=models.CharField(default='Совокупные ежемесячные обязательства (за исключением алиментов)', max_length=200),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='relations_phone_number',
            field=models.CharField(default='89276976453', max_length=12),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='work_expireance_lw_month',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='work_expireance_lw_years',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='work_expireance_month',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='work_expireance_years',
            field=models.CharField(default='00', max_length=2),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='work_phone_number',
            field=models.CharField(default='89276976453', max_length=12),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='work_type_other',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='additionalclientinfo',
            name='сont_phone_number',
            field=models.CharField(default='89276976453', max_length=12),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='site',
            field=models.CharField(default='1345678911', max_length=100),
        ),
        migrations.AddField(
            model_name='passport',
            name='date_of',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
